apiVersion: v1
kind: Service
metadata:
  name: ftgo-api-gateway
spec:
  type: NodePort
  ports:
  - nodePort: 30000 # 광역 클러스터 포트
    port: 80
    targetPort: 8080
  selector:
    svc: ftgo-api-gateway
---
