apiVersion: v1
kind: Service
metadata:
  name: ftgo-order-service
  labels:
    application: ftgo
    app: ftgo
spec:
  ports:
  - name: httpport
    port: 8080
    targetPort: 8080
  - name: metricport
    port: 8081
    targetPort: 8080
    protocol: TCP
  selector:
    svc: ftgo-order-service
---
#apiVersion: extensions/v1beta1
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftgo-order-service
  labels:
    application: ftgo
spec:
  selector:
    matchLabels:
      svc: ftgo-order-service
  replicas: 1
  strategy:
    rollingUpdate:
      maxUnavailable: 0
  template:
    metadata:
      labels:
        svc: ftgo-order-service
        application: ftgo
    spec:
      containers:
      - name: ftgo-order-service
        image: jzzzin/ftgo-order-service:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          name: httpport
        env:
          - name: JAVA_OPTS
            value: "-Dsun.net.inetaddr.ttl=30"
#          - name: SPRING_DATASOURCE_URL
#            value: jdbc:mysql://ftgo-mysql/eventuate
#          - name: SPRING_DATASOURCE_USERNAME
#            valueFrom:
#              secretKeyRef:
#                name: ftgo-db-secret
#                key: username
#          - name: SPRING_DATASOURCE_PASSWORD
#            valueFrom:
#              secretKeyRef:
#                name: ftgo-db-secret
#                key: password
          - name: SPRING_DATASOURCE_URL
            value: jdbc:mysql://ftgo-mysql/ftgo_order_service
          - name: SPRING_DATASOURCE_USERNAME
            value: ftgo_order_service_user
          - name: SPRING_DATASOURCE_PASSWORD
            value: ftgo_order_service_password
          - name: SPRING_DATASOURCE_DRIVER_CLASS_NAME
            value: com.mysql.jdbc.Driver
          - name: EVENTUATELOCAL_KAFKA_BOOTSTRAP_SERVERS
            value: ftgo-kafka:9092
          - name: EVENTUATELOCAL_ZOOKEEPER_CONNECTION_STRING
            value: ftgo-zookeeper:2181
          - name: EVENTUATE_DATABASE_SCHEMA
            value: ftgo_order_service
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 20
---